### ISSUE TITLE
Regression on CJuiDialog inserted into yii 1.1.16 

### ISSUE THREAD

**Issue by nmalservet** [yiisoft/yii#3722]
I'm using zii.widgets.jui.CJuiDialog, and that's was working in Yii 1.1.15.
Until i have done the migration in yii 1.1.16, my dialog box wasn't hidden by default, and i have an error in the javascript execution : TypeError: $(...).dialog is not a function

Im' thinking there is a regression introduced into this 1.1.16, probably declaring jquery.ui...

**Comment by nmalservet** [comment]
I had fix this issue with yii 1.1.16 by including this line into my main layout : 
<?php Yii::app()->clientScript->registerCoreScript('jquery');     
Yii::app()->clientScript->registerCoreScript('jquery.ui');?>

**Comment by marcovtwout** [comment]
Did you read the note about the upgraded jQuery UI? https://raw.githubusercontent.com/yiisoft/yii/1.1.16/UPGRADE

Is the error caused in your own code or in Yii framework code?

**Comment by nmalservet** [comment]
Thanks, i had read this note.
This error is on Yii frameawork 1.1.16 i think, because with yii 1.1.15, this dialog box works fine without including the code lines of registring core script for jquery.
It's not a big problem because i can solve it including two lines in my main layout. But i'm asking why jquery is not included in the same way than the olders versions...

**Comment by marcovtwout** [comment]
jQuery 1.x versions have never been fully backwards compatible, and usually have these upgrade guides. So in theory you're right, but that means Yii could never update jQuery AND keep full backwards compatibility at the same time.

Yii 1.x has updated jQuery versions before.

The question remaining, is your posted issue a problem in the Yii core code, or in your specific project? Could you please post a minimal example illustrating the problem?

**Comment by samdark** [comment]
Can't reproduce it with the info provided.
